/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pruebasfiguras;

/**
 *
 * @author Christopher
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtRadioCirculo = new javax.swing.JTextField();
        txtAreaCirculo = new javax.swing.JTextField();
        txtPerimetroCirculo = new javax.swing.JTextField();
        btnAreaCirculo = new javax.swing.JButton();
        btnPerimetroCirculo = new javax.swing.JButton();
        btbBorrarCirculo = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtLadoCuadrado = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtAreaCuadrado = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtPerimetroCuadrado = new javax.swing.JTextField();
        btnAreaCuadrado = new javax.swing.JButton();
        btnPerimetroCuadrado = new javax.swing.JButton();
        btbBorrarCuadrado = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtBaseRectangulo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtAlturaRectangulo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtAreaRectangulo = new javax.swing.JTextField();
        btnAreaRectangulo = new javax.swing.JButton();
        btnPerimetroRectangulo = new javax.swing.JButton();
        btbBorrarRectangulo = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtPerimetroRectangulo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtBaseTrianguloRectangulo = new javax.swing.JTextField();
        txtAlturaTrianguloRectangulo = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtAreaTrianguloRectangulo = new javax.swing.JTextField();
        txtPerimetroTrianguloRectangulo = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        btnAreaTrianguloRectangulo = new javax.swing.JButton();
        btnPerimetroTrianguloRectangulo = new javax.swing.JButton();
        btbBorrarTrianguloRectangulo = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        txtHipotenusaTrianguloRectangulo = new javax.swing.JTextField();
        btnHipotenusaTrianguloRectangulo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Radio");

        jLabel2.setText("Area");

        jLabel3.setText("Perimetro");

        txtRadioCirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRadioCirculoActionPerformed(evt);
            }
        });

        txtAreaCirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAreaCirculoActionPerformed(evt);
            }
        });

        txtPerimetroCirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPerimetroCirculoActionPerformed(evt);
            }
        });

        btnAreaCirculo.setText("Calcular area");
        btnAreaCirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAreaCirculoActionPerformed(evt);
            }
        });

        btnPerimetroCirculo.setText("Calcular perimetro");
        btnPerimetroCirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerimetroCirculoActionPerformed(evt);
            }
        });

        btbBorrarCirculo.setText("Borrar");
        btbBorrarCirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbBorrarCirculoActionPerformed(evt);
            }
        });

        jLabel4.setText("Circulo");

        jLabel9.setText("Cuadrado");

        jLabel10.setText("Lado");

        txtLadoCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLadoCuadradoActionPerformed(evt);
            }
        });

        jLabel11.setText("Area");

        jLabel12.setText("Perimetro");

        btnAreaCuadrado.setText("Calcular area");
        btnAreaCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAreaCuadradoActionPerformed(evt);
            }
        });

        btnPerimetroCuadrado.setText("Calcular perimetro");
        btnPerimetroCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerimetroCuadradoActionPerformed(evt);
            }
        });

        btbBorrarCuadrado.setText("Borrar");
        btbBorrarCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbBorrarCuadradoActionPerformed(evt);
            }
        });

        jLabel5.setText("Rectangulo");

        jLabel6.setText("Base");

        txtBaseRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBaseRectanguloActionPerformed(evt);
            }
        });

        jLabel7.setText("Altura");

        txtAlturaRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlturaRectanguloActionPerformed(evt);
            }
        });

        jLabel8.setText("Area");

        txtAreaRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAreaRectanguloActionPerformed(evt);
            }
        });

        btnAreaRectangulo.setText("Calcular area");
        btnAreaRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAreaRectanguloActionPerformed(evt);
            }
        });

        btnPerimetroRectangulo.setText("Calcular perimetro");
        btnPerimetroRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerimetroRectanguloActionPerformed(evt);
            }
        });

        btbBorrarRectangulo.setText("Borrar");
        btbBorrarRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbBorrarRectanguloActionPerformed(evt);
            }
        });

        jLabel13.setText("Perimetro");

        txtPerimetroRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPerimetroRectanguloActionPerformed(evt);
            }
        });

        jLabel14.setText("Triangulo Rectangulo");

        jLabel15.setText("Base");

        txtBaseTrianguloRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBaseTrianguloRectanguloActionPerformed(evt);
            }
        });

        txtAlturaTrianguloRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlturaTrianguloRectanguloActionPerformed(evt);
            }
        });

        jLabel16.setText("Altura");

        jLabel17.setText("Area");

        txtAreaTrianguloRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAreaTrianguloRectanguloActionPerformed(evt);
            }
        });

        txtPerimetroTrianguloRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPerimetroTrianguloRectanguloActionPerformed(evt);
            }
        });

        jLabel18.setText("Perimetro");

        btnAreaTrianguloRectangulo.setText("Calcular area");
        btnAreaTrianguloRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAreaTrianguloRectanguloActionPerformed(evt);
            }
        });

        btnPerimetroTrianguloRectangulo.setText("Calcular perimetro");
        btnPerimetroTrianguloRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerimetroTrianguloRectanguloActionPerformed(evt);
            }
        });

        btbBorrarTrianguloRectangulo.setText("Borrar");
        btbBorrarTrianguloRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbBorrarTrianguloRectanguloActionPerformed(evt);
            }
        });

        jLabel19.setText("Hipotenusa");

        txtHipotenusaTrianguloRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHipotenusaTrianguloRectanguloActionPerformed(evt);
            }
        });

        btnHipotenusaTrianguloRectangulo.setText("Calcular Hipotenusa");
        btnHipotenusaTrianguloRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHipotenusaTrianguloRectanguloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnAreaCirculo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPerimetroCirculo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btbBorrarCirculo))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtRadioCirculo, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                        .addComponent(txtAreaCirculo)
                                        .addComponent(txtPerimetroCirculo)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtLadoCuadrado, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                        .addComponent(txtAreaCuadrado)
                                        .addComponent(txtPerimetroCuadrado))
                                    .addComponent(jLabel9)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAreaCuadrado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPerimetroCuadrado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btbBorrarCuadrado))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel13))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtBaseRectangulo, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                        .addComponent(txtAlturaRectangulo)
                                        .addComponent(txtAreaRectangulo)
                                        .addComponent(txtPerimetroRectangulo))
                                    .addComponent(jLabel5)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAreaRectangulo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPerimetroRectangulo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btbBorrarRectangulo)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel19))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtBaseTrianguloRectangulo, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                        .addComponent(txtAlturaTrianguloRectangulo)
                                        .addComponent(txtAreaTrianguloRectangulo)
                                        .addComponent(txtPerimetroTrianguloRectangulo)
                                        .addComponent(txtHipotenusaTrianguloRectangulo))
                                    .addComponent(jLabel14)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAreaTrianguloRectangulo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPerimetroTrianguloRectangulo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btbBorrarTrianguloRectangulo))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(btnHipotenusaTrianguloRectangulo)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtRadioCirculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtAreaCirculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtPerimetroCirculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAreaCirculo)
                            .addComponent(btnPerimetroCirculo)
                            .addComponent(btbBorrarCirculo)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(txtLadoCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtAreaCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtPerimetroCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAreaCuadrado)
                            .addComponent(btnPerimetroCuadrado)
                            .addComponent(btbBorrarCuadrado))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txtBaseRectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtAlturaRectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtAreaRectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtPerimetroRectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAreaRectangulo)
                            .addComponent(btnPerimetroRectangulo)
                            .addComponent(btbBorrarRectangulo)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(txtBaseTrianguloRectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txtAlturaTrianguloRectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(txtAreaTrianguloRectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(txtPerimetroTrianguloRectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(txtHipotenusaTrianguloRectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAreaTrianguloRectangulo)
                            .addComponent(btnPerimetroTrianguloRectangulo)
                            .addComponent(btbBorrarTrianguloRectangulo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHipotenusaTrianguloRectangulo)))
                .addContainerGap(142, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAreaCirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAreaCirculoActionPerformed
        // TODO add your handling code here:
        double area;
        int radio = Integer.parseInt(txtRadioCirculo.getText());
        Circulo figura1 = new Circulo(radio);
        area = figura1.calcularArea();
        txtAreaCirculo.setText(String.valueOf(area));
    }//GEN-LAST:event_btnAreaCirculoActionPerformed

    private void btnPerimetroCirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerimetroCirculoActionPerformed
        // TODO add your handling code here:
        double perimetro;
        int radio = Integer.parseInt(txtRadioCirculo.getText());
        Circulo figura1 = new Circulo(radio);
        perimetro = figura1.calcularPerimetro();
        txtPerimetroCirculo.setText(String.valueOf(perimetro));
    }//GEN-LAST:event_btnPerimetroCirculoActionPerformed

    private void btbBorrarCirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbBorrarCirculoActionPerformed
        // TODO add your handling code here:
        txtRadioCirculo.setText("");
        txtAreaCirculo.setText("");
        txtPerimetroCirculo.setText("");
        
    }//GEN-LAST:event_btbBorrarCirculoActionPerformed

    private void btnAreaCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAreaCuadradoActionPerformed
        // TODO add your handling code here:
        double area_cuadrado;
        int lado = Integer.parseInt(txtLadoCuadrado.getText());
        Cuadrado figura2 = new Cuadrado(lado);
        area_cuadrado = figura2.calcularArea();
        txtAreaCuadrado.setText(String.valueOf(area_cuadrado));
    }//GEN-LAST:event_btnAreaCuadradoActionPerformed

    private void btnPerimetroCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerimetroCuadradoActionPerformed
        // TODO add your handling code here:
        double perimetro_cuadrado;
        int lado = Integer.parseInt(txtLadoCuadrado.getText());
        Cuadrado figura2 = new Cuadrado(lado);
        perimetro_cuadrado = figura2.calcularPerimetro();
        txtPerimetroCuadrado.setText(String.valueOf(perimetro_cuadrado));
    }//GEN-LAST:event_btnPerimetroCuadradoActionPerformed

    private void btbBorrarCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbBorrarCuadradoActionPerformed
        // TODO add your handling code here:
        txtLadoCuadrado.setText("");
        txtAreaCuadrado.setText("");
        txtPerimetroCuadrado.setText("");
    }//GEN-LAST:event_btbBorrarCuadradoActionPerformed

    private void txtLadoCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLadoCuadradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLadoCuadradoActionPerformed

    private void txtRadioCirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRadioCirculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRadioCirculoActionPerformed

    private void txtAreaCirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAreaCirculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAreaCirculoActionPerformed

    private void txtPerimetroCirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPerimetroCirculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPerimetroCirculoActionPerformed

    private void txtBaseRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBaseRectanguloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBaseRectanguloActionPerformed

    private void txtAlturaRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlturaRectanguloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlturaRectanguloActionPerformed

    private void txtAreaRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAreaRectanguloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAreaRectanguloActionPerformed

    private void btnAreaRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAreaRectanguloActionPerformed
        // TODO add your handling code here:
        double area_rectangulo;
        int base_rectangulo = Integer.parseInt(txtBaseRectangulo.getText());
        int altura_rectangulo = Integer.parseInt(txtAlturaRectangulo.getText());
        Rectangulo figura3 = new Rectangulo(base_rectangulo,altura_rectangulo);
        area_rectangulo = figura3.calcularArea();
        txtAreaRectangulo.setText(String.valueOf(area_rectangulo));
    }//GEN-LAST:event_btnAreaRectanguloActionPerformed

    private void btnPerimetroRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerimetroRectanguloActionPerformed
        // TODO add your handling code here:
        double perimetro_rectangulo;
        int base_rectangulo = Integer.parseInt(txtBaseRectangulo.getText());
        int altura_rectangulo = Integer.parseInt(txtAlturaRectangulo.getText());
        Rectangulo figura3 = new Rectangulo(base_rectangulo,altura_rectangulo);
        perimetro_rectangulo = figura3.calcularPerimetro();
        txtPerimetroRectangulo.setText(String.valueOf(perimetro_rectangulo));
    }//GEN-LAST:event_btnPerimetroRectanguloActionPerformed

    private void btbBorrarRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbBorrarRectanguloActionPerformed
        // TODO add your handling code here:
        txtBaseRectangulo.setText("");
        txtAlturaRectangulo.setText("");
        txtAreaRectangulo.setText("");
        txtPerimetroRectangulo.setText("");
    }//GEN-LAST:event_btbBorrarRectanguloActionPerformed

    private void txtPerimetroRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPerimetroRectanguloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPerimetroRectanguloActionPerformed

    private void txtBaseTrianguloRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBaseTrianguloRectanguloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBaseTrianguloRectanguloActionPerformed

    private void txtAlturaTrianguloRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlturaTrianguloRectanguloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlturaTrianguloRectanguloActionPerformed

    private void txtAreaTrianguloRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAreaTrianguloRectanguloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAreaTrianguloRectanguloActionPerformed

    private void txtPerimetroTrianguloRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPerimetroTrianguloRectanguloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPerimetroTrianguloRectanguloActionPerformed

    private void btnAreaTrianguloRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAreaTrianguloRectanguloActionPerformed
        // TODO add your handling code here:
        double area_triangulo_rectangulo;
        int base_triangulo_rectangulo = Integer.parseInt(txtBaseTrianguloRectangulo.getText());
        int altura_triangulo_rectangulo = Integer.parseInt(txtAlturaTrianguloRectangulo.getText());
        TrianguloRectangulo figura4 = new TrianguloRectangulo(base_triangulo_rectangulo,altura_triangulo_rectangulo);
        area_triangulo_rectangulo = figura4.calcularArea();
        txtAreaTrianguloRectangulo.setText(String.valueOf(area_triangulo_rectangulo));
    }//GEN-LAST:event_btnAreaTrianguloRectanguloActionPerformed

    private void btnPerimetroTrianguloRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerimetroTrianguloRectanguloActionPerformed
        // TODO add your handling code here:
        double perimetro_triangulo_rectangulo;
        int base_triangulo_rectangulo = Integer.parseInt(txtBaseTrianguloRectangulo.getText());
        int altura_triangulo_rectangulo = Integer.parseInt(txtAlturaTrianguloRectangulo.getText());
        TrianguloRectangulo figura4 = new TrianguloRectangulo(base_triangulo_rectangulo,altura_triangulo_rectangulo);
        perimetro_triangulo_rectangulo = figura4.calcularPerimetro();
        txtPerimetroTrianguloRectangulo.setText(String.valueOf(perimetro_triangulo_rectangulo));
    }//GEN-LAST:event_btnPerimetroTrianguloRectanguloActionPerformed

    private void btbBorrarTrianguloRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbBorrarTrianguloRectanguloActionPerformed
        // TODO add your handling code here:
        txtBaseTrianguloRectangulo.setText("");
        txtAlturaTrianguloRectangulo.setText("");
        txtAreaTrianguloRectangulo.setText("");
        txtPerimetroTrianguloRectangulo.setText("");
        txtHipotenusaTrianguloRectangulo.setText("");
    }//GEN-LAST:event_btbBorrarTrianguloRectanguloActionPerformed

    private void txtHipotenusaTrianguloRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHipotenusaTrianguloRectanguloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHipotenusaTrianguloRectanguloActionPerformed

    private void btnHipotenusaTrianguloRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHipotenusaTrianguloRectanguloActionPerformed
        // TODO add your handling code here:
        double hipotenusa_triangulo_rectangulo;
        int base_triangulo_rectangulo = Integer.parseInt(txtBaseTrianguloRectangulo.getText());
        int altura_triangulo_rectangulo = Integer.parseInt(txtAlturaTrianguloRectangulo.getText());
        TrianguloRectangulo figura4 = new TrianguloRectangulo(base_triangulo_rectangulo,altura_triangulo_rectangulo);
        hipotenusa_triangulo_rectangulo = figura4.calcularHipotenusa();
        txtHipotenusaTrianguloRectangulo.setText(String.valueOf(hipotenusa_triangulo_rectangulo));
    }//GEN-LAST:event_btnHipotenusaTrianguloRectanguloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbBorrarCirculo;
    private javax.swing.JButton btbBorrarCuadrado;
    private javax.swing.JButton btbBorrarRectangulo;
    private javax.swing.JButton btbBorrarTrianguloRectangulo;
    private javax.swing.JButton btnAreaCirculo;
    private javax.swing.JButton btnAreaCuadrado;
    private javax.swing.JButton btnAreaRectangulo;
    private javax.swing.JButton btnAreaTrianguloRectangulo;
    private javax.swing.JButton btnHipotenusaTrianguloRectangulo;
    private javax.swing.JButton btnPerimetroCirculo;
    private javax.swing.JButton btnPerimetroCuadrado;
    private javax.swing.JButton btnPerimetroRectangulo;
    private javax.swing.JButton btnPerimetroTrianguloRectangulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtAlturaRectangulo;
    private javax.swing.JTextField txtAlturaTrianguloRectangulo;
    private javax.swing.JTextField txtAreaCirculo;
    private javax.swing.JTextField txtAreaCuadrado;
    private javax.swing.JTextField txtAreaRectangulo;
    private javax.swing.JTextField txtAreaTrianguloRectangulo;
    private javax.swing.JTextField txtBaseRectangulo;
    private javax.swing.JTextField txtBaseTrianguloRectangulo;
    private javax.swing.JTextField txtHipotenusaTrianguloRectangulo;
    private javax.swing.JTextField txtLadoCuadrado;
    private javax.swing.JTextField txtPerimetroCirculo;
    private javax.swing.JTextField txtPerimetroCuadrado;
    private javax.swing.JTextField txtPerimetroRectangulo;
    private javax.swing.JTextField txtPerimetroTrianguloRectangulo;
    private javax.swing.JTextField txtRadioCirculo;
    // End of variables declaration//GEN-END:variables
}
